_part2-start/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('', include('todos.urls')),
    path(settings.ADMIN_URL, admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

_part2-start/todos/urls.py
from django.urls import path

from . import views

app_name = "todos"
urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("add", views.add, name="add"),
    path("<int:pk>/", views.DetailView.as_view(), name="detail"),
]

_part2-start/todos/models.py
from django.db import models


class Task(models.Model):
    title = models.CharField(max_length=255)
    done = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.title}({'✔' if self.done else '✘'})"

    def is_done(self):
        return self.done == True

_part2-start/todos/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views import generic
from .models import Task


class IndexView(generic.ListView):
    template_name = "todos/index.html"
    context_object_name = "all_tasks"

    def get_queryset(self):
        return Task.objects.all()


class DetailView(generic.DetailView):
    model = Task
    template_name = "todos/detail.html"


def add(request):
    title = request.POST["title"]
    task = Task(title=title)
    task.save()
    return redirect("todos:index")

_part2-start/todos/templates/todos/detail.html
{{ task }}

{% comment %} TODO: form to mark as done {% endcomment %}

_part2-start/todos/templates/todos/index.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8"/>
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
        <title>Simple TODO app</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet"/>
    </head>
    <body>
        <div id="wrapper">
            <div class="container">
                <h1 class="mt-4">My TODO</h1>
                <ul>
                    {% for task in all_tasks %}
                    <li>
                        <input class="form-check-input" type="checkbox" value="" disabled {% if task.done %}checked{% endif %}>
                        <a href="{% url 'todos:detail' task.id %}">{{ task.title }}</a>
                    </li>
                    {% endfor %}
                </ul>
            </div>
            <div class="container">
                <h2>Add new task</h2>
                <form action="{% url 'todos:add' %}" method="post">
                    {% csrf_token %}
                    <input type="text" name="title" placeholder="Buy milk">
                    <input type="submit" value="Add">
                </form>
            </div>
        </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>